version: "3.9"
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    container_name: azkaban_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fastapi_db
    ports:
      - "7777:7777"
    depends_on:
      - db

  