version: "3.9"
services:
  server:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: fastapi_db
  app:
    image: my-app
    ports:
      - 13000:8000
      